version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: todolist
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  todolist:
    build:
      context: .
    container_name: todolist_app
    restart: always
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: todolist
      DB_USER: user
      DB_PASSWORD: userpassword
    depends_on:
      - mysql
    ports:
      - "8000:8000"
    entrypoint: ["sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]

volumes:
  mysql_data: